### ISSUE TITLE
Matrix-Algorithmus Fehler

### ISSUE THREAD

**Issue by lschoeb** [mzuenni/ChaosKITs#2]
https://github.com/mzuenni/ContestReference/blob/14e85b0162fd289fb7453e9a0d541a261e3546e8/graph/graph.tex#L89

Sollte hier für den zweiten Anwendungsfall nicht die normale Matrixmultiplikation, also mit Mal statt mit Plus stehen?

**Comment by mzuenni** [comment]
Ja, fixed 874a5628f813c70522a0998c2e3eacbae60d7577
